config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace 'api' do
    namespace 'v1' do
      resources :feeds, only: [:index, :show]
      resources :likes, only: [:index, :show, :create]
      resources :comments, only: [:index, :show, :create]
    end
  end

  get 'likes/index'
  get 'comments/index'
  get 'feeds/index'

  resources :feeds, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :likes
  has_many :comments
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :feed
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      def index
        comments = Comment.order('created_at DESC')
        render json: {status: 'SUCCESS', message:'Loaded Comments', data:comments},status: :ok
      end

      def show
        comment = Comment.find(params[:id])
        render json: {status: 'SUCCESS', message:'Loaded Comment', data:comment},status: :ok
      end

      def create
        comment = Comment.new(comment_params)
        if comment.save
          render json: {status: 'SUCCESS', message:'Saved Comment', data:comment},status: :ok
        else
          render json: {status: 'ERROR', message:'Comment not saved', data:comment.errors},status: :unprocessable_entity
        end
      end

      private

      def comment_params
        params.permit(:feed_id, :user_id, :content)
      end

    end
  end
end

app/controllers/api/v1/feeds_controller.rb
module Api
  module V1
    class FeedsController < ApplicationController
      def index
        feeds = Feed.order('created_at DESC');
        render json: {status: 'SUCCESS', message:'Loaded Feeds', data:feeds},status: :ok
      end

      def show
        feed = Feed.find(params[:id])
        render json: {status: 'SUCCESS', message:'Loaded Feed', data:feed},status: :ok
      end
    end
  end
end

app/controllers/api/v1/likes_controller.rb
module Api
  module V1
    class LikesController < ApplicationController
      def index
        likes = Like.order('created_at DESC');
        render json: {status: 'SUCCESS', message:'Loaded Likes', data:likes},status: :ok
      end

      def show
        like = Like.find(params[:id])
        render json: {status: 'SUCCESS', message:'Loaded Like', data:like},status: :ok
      end

      def create
        like = Like.new(like_params)
        if like.save
          render json: {status: 'SUCCESS', message:'Saved Like', data:like},status: :ok
        else
          render json: {status: 'ERROR', message:'Like not saved', data:like.errors},status: :unprocessable_entity
        end
      end

      private

      def like_params
        params.permit(:feed_id, :user_id, :like)
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.order('created_at DESC')
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  include ApplicationHelper

  def index
    @feeds = Feed.order('id')
  end

  def create
    get_data_json(params[:feed][:url])
    redirect_to root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @likes = Like.order('created_at DESC');
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  require 'uri'
  require 'net/http'
  require 'json'

  def get_data_json(url)
    url = URI.parse(url)
    if url.kind_of?(URI::HTTP) or url.kind_of?(URI::HTTPS)
      result = Net::HTTP.get_response(url)
      result = JSON.parse(result.body)

      if !result.nil? && !result['items'].nil?
        result['items'].each do |item|
          Feed.create(date_feed: item['fecha'], title: item['title'], image: item['image'], content: item['content'], all_content: item['all_content'],
          category: item['link'])
        end
      else
        return false
      end
    end
  end
end

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>user_id</th>
      <th>content</th>
      <th>feed</th>
      <th>JSON</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.content %></td>
        <td><%= comment.feed_id %></td>
        <td><%= link_to 'Json(' + comment.id.to_s + ')', api_v1_comment_path(comment) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'ROOT', root_path %>

app/views/feeds/index.html.erb
<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>date_feed</th>
      <th>title</th>
      <th>image</th>
      <th>content</th>
      <th>all_content</th>
      <th>Category</th>
      <th>JSON</th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.id %></td>
        <td><%= feed.date_feed %></td>
        <td><%= feed.title[0,20] %></td>
        <td><%= image_tag(feed.image,size:"64x64") if feed.image.present? %></td>
        <td><%= feed.content[0,20] %></td>
        <td><%= feed.all_content[0,20] %></td>
        <td><%= feed.category[0,20] %></td>
        <td><%= link_to 'Json(' + feed.id.to_s + ')', api_v1_feed_path(feed) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'ROOT', root_path %>

app/views/home/index.html.erb
<h1>Api ROOT</h1>

<div>
  <p>Total de Feeds: <strong><%= Feed.all.size %></strong>
    <%= link_to "Listar Feeds JSON", api_v1_feeds_path %>
    <%= link_to "Listar Feeds HTML", feeds_index_path %>
  </p>
</div>

<br>
<div>
  <p>Total de Comentarios: <strong><%= Comment.all.size %></strong>
    <%= link_to "Listar Comentarios JSON", api_v1_comments_path %>
    <%= link_to "Listar Comentarios HTML", comments_index_path %>
  </p>
  <p>New <span>Enviar Post Url : http://localhost:3000/api/v1/comments </span>
    ->
    {
  	"feed_id":"integer",
  	"user_id":"integer",
  	"content":"text"
    }
  </p>
</div>

<br>
<div>
  <p>Total de Likes : <strong><%= Like.all.size %></strong>
    <%= link_to "Listar Me Gusta JSON", api_v1_likes_path %>
    <%= link_to "Listar Me Gusta HTML", likes_index_path %>
  </p>
  <p>New <span>Enviar Post Url : http://localhost:3000/api/v1/likes </span>
    ->
    {
	  "feed_id":"integer",
	  "user_id":"integer",
	  "like":"boolean"
    }
  </p>
</div>


<br>
<div>

  <p>Parse File Items</p>
  <form action="/feeds" method="post">
    <input type="url" name="feed[url]" placeholder="URL" value="https://www.teleton.cl/feed/?json">
    <input type="submit" name="commit" value="enviar">
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teleton API</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice">Informacion : Importante <%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/index.html.erb
<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>user_id</th>
      <th>feed</th>
      <th>Like</th>
      <th>JSON</th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.id %></td>
        <td><%= like.user_id %></td>
        <td><%= like.feed_id %></td>
        <td><%= like.like %></td>
        <td><%= link_to 'Json(' + like.id.to_s + ')', api_v1_like_path(like) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'ROOT', root_path %>